# 1. Cargamos los módulos necesarios de Apache para que funcione el SSL y el Proxy
LoadModule ssl_module modules/mod_ssl.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

# 2. Le decimos a Apache que escuche única y exclusivamente por el puerto seguro 443
Listen 443

# 3. Configuración del Servidor Virtual Seguro para tu dominio
<VirtualHost *:443>
    ServerName reservaya.es

    # Activamos el motor SSL/TLS
    SSLEngine on
    
    # Le indicamos las rutas internas del contenedor donde están tus certificados
    SSLCertificateFile "/usr/local/apache2/conf/ssl/reservaya.crt"
    SSLCertificateKeyFile "/usr/local/apache2/conf/ssl/reservaya.key"

    # CONFIGURACIÓN DEL PROXY INVERSO:
    # Todo lo que entre por HTTPS a reservaya.es se reenvía por dentro al contenedor php_app por el puerto 80
    ProxyPreserveHost On
    ProxyPass / http://php_app:80/
    ProxyPassReverse / http://php_app:80/

    # Directiva de seguridad para evitar que usen nuestro Apache como proxy abierto hacia internet
    ProxyRequests Off
</VirtualHost>
