# Solo escuchamos en el 443 aquí, el 80 ya lo hace Apache por defecto
Listen 443

# VirtualHost para HTTP (Puerto 80)
# Útil si el tráfico entra por el túnel de Cloudflare en modo Flexible
<VirtualHost *:80>
    ServerName reservayasamuel.es
    ProxyPreserveHost On
    ProxyPass / http://php_app:80/
    ProxyPassReverse / http://php_app:80/
</VirtualHost>

# VirtualHost para HTTPS (Puerto 443)
# Este es el que te da el candado de seguridad
<VirtualHost *:443>
    ServerName reservayasamuel.es
    SSLEngine on
    SSLCertificateFile "/usr/local/apache2/conf/ssl/reservaya.crt"
    SSLCertificateKeyFile "/usr/local/apache2/conf/ssl/reservaya.key"
    
    ProxyPreserveHost On
    ProxyPass / http://php_app:80/
    ProxyPassReverse / http://php_app:80/
</VirtualHost>
